"""Structure metrics: the tree-sitter lane.

The concentration figure is a share of a distribution built by walking every parse tree in
the repository, so a single node name missing from a table, or one directory pruned that
should not have been, moves the number without raising anything. The fixtures below are
therefore one per edge the walk has, and each assertion says what its fixture is for.
"""

from __future__ import annotations

import sys

import pytest

from hazina_scan import structure

# --- the trees, one per edge the walk has ------------------------------------------

#: Five grammars and a tier the parser cannot reach: Python, TypeScript, Go, Rust, a
#: notebook whose code cells are the only thing counted, and a Vala file that raises the
#: file and line counts without ever being handed to a parser.
MULTI_FILES = {
    "src/loader.py": "import json\n"
    "\n"
    "\n"
    "def load(path):\n"
    "    try:\n"
    "        with open(path) as fh:\n"
    "            return json.load(fh)\n"
    "    except OSError:\n"
    "        return None\n"
    "\n"
    "\n"
    "def pick(rows, limit):\n"
    "    out = []\n"
    "    for row in rows:\n"
    "        if row.get('ok'):\n"
    "            out.append(row)\n"
    "        elif len(out) >= limit:\n"
    "            break\n"
    "    return out\n",
    "web/classify.ts": "export function classify(n: number): string {\n"
    "  if (n < 0) {\n"
    "    return 'negative';\n"
    "  } else if (n === 0) {\n"
    "    return 'zero';\n"
    "  }\n"
    "  return 'positive';\n"
    "}\n"
    "\n"
    "export const total = (xs: number[]): number => {\n"
    "  let acc = 0;\n"
    "  for (const x of xs) {\n"
    "    acc += x;\n"
    "  }\n"
    "  return acc;\n"
    "};\n",
    "svc/divide.go": "package svc\n"
    "\n"
    'import "errors"\n'
    "\n"
    "func Divide(a, b int) (int, error) {\n"
    "\tif b == 0 {\n"
    '\t\treturn 0, errors.New("divide by zero")\n'
    "\t}\n"
    "\treturn a / b, nil\n"
    "}\n"
    "\n"
    "func Sum(xs []int) int {\n"
    "\tacc := 0\n"
    "\tfor _, x := range xs {\n"
    "\t\tacc += x\n"
    "\t}\n"
    "\treturn acc\n"
    "}\n",
    "core/lib.rs": "pub fn largest(xs: &[i32]) -> Option<i32> {\n"
    "    let mut best = None;\n"
    "    for x in xs {\n"
    "        match best {\n"
    "            Some(b) if b >= *x => {}\n"
    "            _ => best = Some(*x),\n"
    "        }\n"
    "    }\n"
    "    best\n"
    "}\n"
    "\n"
    "pub fn parse_one(s: &str) -> Result<i32, String> {\n"
    "    s.trim().parse::<i32>().map_err(|e| e.to_string())\n"
    "}\n",
    # Markdown cells and outputs are not code and must not reach the line count.
    "notebooks/explore.ipynb": '{"cells": ['
    '{"cell_type": "markdown", "source": ["# heading\\n", "prose that is not code\\n"]},'
    '{"cell_type": "code", "source": ["def mean(xs):\\n", "    if not xs:\\n",'
    ' "        return 0\\n", "    return sum(xs) / len(xs)\\n"],'
    ' "outputs": [{"text": ["0.5\\n"]}]},'
    '{"cell_type": "code", "source": "total = 0\\nfor i in range(3):\\n    total += i\\n"}'
    '], "metadata": {}, "nbformat": 4}\n',
    # Second tier: a real language with no grammar in the pinned pack.
    "legacy/report.vala": "int main (string[] args) {\n"
    "    if (args.length > 1) {\n"
    '        stdout.printf ("%s\\n", args[1]);\n'
    "    }\n"
    "    return 0;\n"
    "}\n",
    "tests/test_loader.py": "def test_load():\n    assert True\n",
    "README.md": "# multi\n",
}

#: Everything that makes the scan report its own bounds: a file over the byte ceiling, a
#: generated file, and a file whose grammar the pinned pack cannot supply.
BOUNDS_FILES = {
    "src/huge.py": "row = 1\n" * 200_000,
    "src/schema_gen.py": "# Code generated by a schema compiler. DO NOT EDIT.\n"
    "def build():\n"
    "    if True:\n"
    "        return 1\n"
    "    return 0\n",
    "src/Legacy.cs": "public class Legacy {\n"
    "    public int Pick(int n) {\n"
    "        if (n > 0) { return n; }\n"
    "        return 0;\n"
    "    }\n"
    "}\n",
    "src/ok.py": "def ok(n):\n    if n:\n        return n\n    return 0\n",
}

#: Source with no function in it anywhere, which is the one case where the concentration
#: figure is withheld rather than reported as zero.
NO_FUNCTION_FILES = {
    "src/constants.py": "ALPHA = 1\nBETA = 2\nGAMMA = ALPHA + BETA\n",
    "src/schema.sql": "SELECT id, name FROM customers WHERE active = 1;\n",
}

#: More source files than one scan looks at. The walk is `Path.rglob`, so on one filesystem
#: the files arrive in the same order every run and the cap always falls in the same place
#: -- which is what makes a capped scan a repeatable measurement rather than a sample.
CAPPED_FILES = {
    f"src/mod{i}.py": f"def f{i}(n):\n    if n:\n        return {i}\n    return 0\n"
    for i in range(structure.MAX_FILES + 100)
}


# --- the measurements --------------------------------------------------------------------


def test_collect_on_python(py_repo):
    out = structure.collect(py_repo)
    assert out["ok"] and out["structure_probe_mode"] == "deterministic"
    assert out["prod_loc"] > 0 and out["test_files"] == 1
    assert 0.0 <= out["decisions_gini_top1pct"] <= 1.0


def test_no_path_leaves_the_probe(py_repo):
    """Nothing in the returned dict may name a file: the block is counts and plain words."""
    out = structure.collect(py_repo)
    flat = " ".join(str(v) for v in out.values())
    for token in ("core.py", "src", "demo", str(py_repo)):
        assert token not in flat


def test_multi_language_tree_is_parsed(repo_builder):
    repo = repo_builder(MULTI_FILES)
    out = structure.collect(repo)
    # Python, TypeScript, Go, Rust and the notebook parse; the Vala file is counted and
    # never parsed; the test file is counted apart from all of them.
    assert out["n_files_parsed"] == 5
    assert out["source_files_unparsed"] == 1
    assert out["source_files"] == 6
    assert out["test_files"] == 1
    assert out["n_files_parse_failed"] == 0
    assert out["n_functions_seen"] >= 8
    assert out["error_handling_per_kloc"] > 0


def test_notebook_counts_code_cells_only(repo_builder):
    """A notebook is JSON on disk and code to everyone who works on it. Counting the raw
    JSON would report output blobs and base64 images as production lines."""
    repo = repo_builder({"nb/one.ipynb": MULTI_FILES["notebooks/explore.ipynb"]})
    out = structure.collect(repo)
    assert out["source_files"] == 1 and out["n_files_parsed"] == 1
    # four lines of function plus three of loop, and not one line of prose or output
    assert out["prod_loc"] == 8


def test_notebook_without_code_cells_is_prose(repo_builder):
    repo = repo_builder(
        {
            "nb/prose.ipynb": '{"cells": [{"cell_type": "markdown", "source": ["# hi\\n"]}]}\n',
            "nb/broken.ipynb": "not json at all\n",
            "src/ok.py": "def ok():\n    return 1\n",
        }
    )
    out = structure.collect(repo)
    assert out["source_files"] == 1


def test_bounds_are_reported_never_applied_silently(repo_builder):
    repo = repo_builder(BOUNDS_FILES)
    out = structure.collect(repo)
    assert out["bounds"] == (
        "1 files over 1000KB skipped; 1 generated files skipped; 1 files failed to parse"
    )
    assert out["source_files"] == 2  # the C# file counts; only its parse failed
    assert out["n_files_parsed"] == 1


def test_the_file_cap_is_reported(repo_builder):
    repo = repo_builder(CAPPED_FILES)
    out = structure.collect(repo)
    assert out["source_files"] == structure.MAX_FILES
    assert out["bounds"] == (
        f"file cap {structure.MAX_FILES} reached; "
        f"covers the first {structure.MAX_FILES} source files"
    )


def test_no_functions_leaves_the_share_unscored(repo_builder):
    repo = repo_builder(NO_FUNCTION_FILES)
    out = structure.collect(repo)
    assert out["decisions_gini_top1pct"] is None
    assert out["note"] == "no functions parsed; concentration criterion unscored rather than zero"
    assert out["n_functions_seen"] == 0
    assert out["prod_loc"] == 4


def test_empty_tree_reports_zero_rather_than_a_rate(repo_builder):
    repo = repo_builder({"README.md": "# nothing\n"})
    out = structure.collect(repo)
    assert out["ok"] and out["source_files"] == 0 and out["prod_loc"] == 0
    # No code means no denominator: a rate of 0.0 would be a claim nobody measured.
    assert out["error_handling_per_kloc"] is None


def test_vendored_and_generated_paths_are_not_first_party(repo_builder):
    repo = repo_builder(
        {
            "src/app.py": "def app():\n    return 1\n",
            "node_modules/pkg/index.js": "module.exports = 1\n",
            "vendor/lib/thing.go": "package lib\n",
            "src/app.min.js": "var a=1\n",
        }
    )
    out = structure.collect(repo)
    assert out["source_files"] == 1


def test_missing_parser_is_unscored_not_zero(py_repo, monkeypatch):
    """A parser that is not installed is a fact about the operator's machine, not about
    the repository, so nothing is measured and nothing is reported as zero."""
    monkeypatch.setitem(sys.modules, "tree_sitter_language_pack", None)
    out = structure.collect(py_repo)
    assert out == {"probe": "code_structure", "ok": False, "error": out["error"]}
    assert "parser unavailable" in out["error"]


# --- the pieces --------------------------------------------------------------------------


def test_gini_top_is_a_share():
    assert structure.gini_top([]) == 0.0
    assert structure.gini_top([0, 0, 0]) == 0.0
    assert structure.gini_top([10]) == 1.0
    # 1% of 100 functions is one function, and it holds 100 of the 199 decisions
    assert structure.gini_top([100] + [1] * 99) == pytest.approx(100 / 199)


def test_ambiguous_extensions_are_resolved_from_the_bytes():
    assert structure.resolve_m(b"#import <Foundation/Foundation.h>\n") == "objc"
    assert structure.resolve_m(b"function y = f(x)\ny = x + 1;\nend\n") == "matlab"
    assert structure.resolve_v(b"module top;\nendmodule\n") == "verilog"
    assert structure.resolve_v(b"fn main() {\n}\n") == "v"
    assert structure.resolve_pl(b"parent(tom, bob).\nancestor(X, Y) :- parent(X, Y).\n") == "prolog"
    assert structure.resolve_pl(b"use strict;\nsub main { return 1; }\n") == "perl"


def test_notebook_source_extracts_code_cells():
    assert structure.notebook_source(b"{ not json") == b""
    assert structure.notebook_source(b'{"cells": []}') == b""
    # Valid JSON that is not an object: malformed notebook JSON is read as no code. A
    # probe that cannot measure a file has to say so rather than take the whole scan down
    # with it, so the type error is caught here and the file contributes nothing.
    assert structure.notebook_source(b"[1, 2, 3]") == b""
    src = structure.notebook_source(
        b'{"cells": [{"cell_type": "code", "source": ["a = 1\\n"]},'
        b' {"cell_type": "markdown", "source": ["prose"]},'
        b' {"cell_type": "code", "source": "b = 2\\n"}]}'
    )
    assert src == b"a = 1\n\nb = 2\n"
